export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const UPDATE_TEAMS_SUCCESS = 'UPDATE_TEAMS_SUCCESS';
export const CREATE_TEAMS_SUCCESS = 'CREATE_TEAMS_SUCCESS';